server:
  port: 80


spring:
    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://111.229.245.32:3305/blog_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: xiao20010301


mybatis:
  type-aliases-package: com.blog.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl